export enum CurbyCoinTransactionTypeKey {
  THANKS_FOR_JOINING = 'THANKS_FOR_JOINING',
  THANKS_FOR_THE_FEEDBACK = 'THANKS_FOR_THE_FEEDBACK',
  YOU_POSTED_YOUR_FIRST_FREE_ITEM = 'YOU_POSTED_YOUR_FIRST_FREE_ITEM',
  YOU_POSTED_A_FREE_ITEM = 'YOU_POSTED_A_FREE_ITEM',
  YOUR_FREE_ITEM_WAS_SAVED = 'YOUR_FREE_ITEM_WAS_SAVED',
  YOU_SAVED_YOUR_FIRST_FREE_ITEM = 'YOU_SAVED_YOUR_FIRST_FREE_ITEM',
  YOU_SAVED_A_FREE_ITEM = 'YOU_SAVED_A_FREE_ITEM',
  YOU_TOOK_YOUR_FIRST_FREE_ITEM = 'YOU_TOOK_YOUR_FIRST_FREE_ITEM',
  YOU_TOOK_A_FREE_ITEM = 'YOU_TOOK_A_FREE_ITEM',
  FREE_ITEM_TAKEN_WITHIN_1_HOUR = 'FREE_ITEM_TAKEN_WITHIN_1_HOUR',
  FREE_ITEM_TAKEN_WITHIN_12_HOURS = 'FREE_ITEM_TAKEN_WITHIN_12_HOURS',
  FREE_ITEM_TAKEN_WITHIN_24_HOURS = 'FREE_ITEM_TAKEN_WITHIN_24_HOURS',
  FREE_ITEM_TAKEN_AFTER_24_HOURS = 'FREE_ITEM_TAKEN_AFTER_24_HOURS',
  FREE_ITEM_REPORTED_LEGITIMATELY = 'FREE_ITEM_REPORTED_LEGITIMATELY'
}
